on: push

name: ci

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - rufm-core
          - rufm-cli
          - rufm-import-firefly-iii

        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --manifest-path ${{ matrix.project }}/Cargo.toml

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --manifest-path ${{ matrix.project }}/Cargo.toml

  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - rufm-core
          - rufm-cli
          - rufm-import-firefly-iii

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: rustfmt

      - name: Run fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --verbose --manifest-path ${{ matrix.project }}/Cargo.toml -- --check

  clippy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - rufm-core
          - rufm-cli
          - rufm-import-firefly-iii

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: clippy

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose --manifest-path ${{ matrix.project }}/Cargo.toml --all-features
