on: push

name: ci

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [rufm-core, rufm-cli, rufm-import-firefly-iii]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --manifest-path ${{ matrix.project }}/Cargo.toml
      - name: Run tests
        run: cargo test --verbose --manifest-path ${{ matrix.project }}/Cargo.toml
