on: push

name: ci

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Build
        run: cargo build --all-features --verbose --manifest-path rufm-cli/Cargo.toml

      - name: Run tests
        run: |
          cargo test --manifest-path rufm-core/Cargo.toml
          cargo test --manifest-path rufm-cli/Cargo.toml
          cargo test --manifest-path rufm-import-firefly-iii/Cargo.toml

  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - rufm-core
          - rufm-cli
          - rufm-import-firefly-iii

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: rustfmt

      - name: Run fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --verbose --manifest-path ${{ matrix.project }}/Cargo.toml -- --check

  clippy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - rufm-core
          - rufm-cli
          - rufm-import-firefly-iii

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: clippy

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose --manifest-path ${{ matrix.project }}/Cargo.toml --all-features
